package mongodb

import (
	"github.com/authzed/spicedb/internal/datastore/common"
	"github.com/authzed/spicedb/pkg/datastore/options"
	"github.com/authzed/spicedb/pkg/datastore/queryshape"
)

// Index names are auto-generated by MongoDB based on field names and sort order.
// These match the indexes created in mongodb.go createIndexes().
const (
	// IndexNamePrimaryKey is the compound unique index on all relationship fields.
	// Created from: {namespace: 1, resource_id: 1, relation: 1, subject_namespace: 1, subject_object_id: 1, subject_relation: 1, deleted_revision: 1}
	IndexNamePrimaryKey = "namespace_1_resource_id_1_relation_1_subject_namespace_1_subject_object_id_1_subject_relation_1_deleted_revision_1"

	// IndexNameByNamespace is the index for queries filtering by namespace only.
	// Created from: {namespace: 1, deleted_revision: 1}
	IndexNameByNamespace = "namespace_1_deleted_revision_1"

	// IndexNameByNamespaceRelation is the index for queries filtering by namespace and relation.
	// Created from: {namespace: 1, relation: 1, deleted_revision: 1}
	IndexNameByNamespaceRelation = "namespace_1_relation_1_deleted_revision_1"

	// IndexNameBySubject is the index for reverse lookups by subject.
	// Created from: {subject_namespace: 1, deleted_revision: 1}
	IndexNameBySubject = "subject_namespace_1_deleted_revision_1"
)

// IndexPrimaryKey is the primary compound index covering all relationship fields.
// Best for queries that specify resource type, resource ID, and relation.
var IndexPrimaryKey = common.IndexDefinition{
	Name: IndexNamePrimaryKey,
	Shapes: []queryshape.Shape{
		queryshape.CheckPermissionSelectDirectSubjects,
		queryshape.CheckPermissionSelectIndirectSubjects,
		queryshape.AllSubjectsForResources,
	},
	PreferredSortOrder: options.ByResource,
}

// IndexByNamespace is for queries that filter only by namespace (resource type).
var IndexByNamespace = common.IndexDefinition{
	Name: IndexNameByNamespace,
	Shapes: []queryshape.Shape{
		queryshape.FindResourceOfType,
	},
	PreferredSortOrder: options.ByResource,
}

// IndexByNamespaceRelation is for queries that filter by namespace and relation.
var IndexByNamespaceRelation = common.IndexDefinition{
	Name: IndexNameByNamespaceRelation,
	Shapes: []queryshape.Shape{
		queryshape.FindResourceAndSubjectWithRelations,
		queryshape.FindResourceRelationForSubjectRelation,
	},
	PreferredSortOrder: options.ByResource,
}

// IndexBySubject is for reverse lookups starting from the subject side.
var IndexBySubject = common.IndexDefinition{
	Name: IndexNameBySubject,
	Shapes: []queryshape.Shape{
		queryshape.MatchingResourcesForSubject,
		queryshape.FindSubjectOfTypeAndRelation,
	},
	PreferredSortOrder: options.BySubject,
}

// allIndexes contains all defined indexes for MongoDB.
var allIndexes = []common.IndexDefinition{
	IndexPrimaryKey,
	IndexByNamespace,
	IndexByNamespaceRelation,
	IndexBySubject,
}

// NoIndexHint indicates no index hint should be applied.
var NoIndexHint common.IndexingHint = nil

// IndexingHintForQueryShape returns an indexing hint for the given query shape.
// Returns nil if no specific index should be forced for the shape.
func IndexingHintForQueryShape(qs queryshape.Shape) common.IndexingHint {
	switch qs {
	case queryshape.CheckPermissionSelectDirectSubjects:
		return forcedIndex{IndexPrimaryKey}

	case queryshape.CheckPermissionSelectIndirectSubjects:
		return forcedIndex{IndexPrimaryKey}

	case queryshape.AllSubjectsForResources:
		return forcedIndex{IndexPrimaryKey}

	case queryshape.MatchingResourcesForSubject:
		return forcedIndex{IndexBySubject}

	case queryshape.FindResourceOfType:
		return forcedIndex{IndexByNamespace}

	case queryshape.FindResourceAndSubjectWithRelations:
		return forcedIndex{IndexByNamespaceRelation}

	case queryshape.FindSubjectOfTypeAndRelation:
		return forcedIndex{IndexBySubject}

	case queryshape.FindResourceRelationForSubjectRelation:
		return forcedIndex{IndexByNamespaceRelation}

	default:
		// For varying or unspecified shapes, let MongoDB decide
		return NoIndexHint
	}
}
